"""Common constants."""

KEY_KEY = '_KEY_'
KEY_STATUS = '_STATUS_'
KEY_VALUE = '_VALUE_'
KEY_CHILDREN = '_CHILDREN_'
STATUS_STAY = '_STAY_'
STATUS_DEL = '_DEL_'
STATUS_NEW = '_NEW_'
STATUS_CHANGE = '_CHANGE_'
VALUE_STAY = '_STAY_'
VALUE_DEL = '_DEL_'
VALUE_NEW = '_NEW_'
